name: fakhravari
description: Dart extension methods for String and num types, providing utilities like capitalization, number formatting, and validation.
version: 0.0.4
homepage: https://fakhravari.ir
repository: https://github.com/fakhravari/flutter-fakhravari

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  encrypt: ^5.0.3

  # تاریخ
  shamsi_date: ^1.1.1
  hijri_calendar: ^1.0.7+7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: